In [1]:
#Importando as bibliotecas
from numpy import pi 
import numpy as np

In [2]:
print('Versão de numpy e:', np.__version__)

Versão de numpy e: 1.18.5


In [3]:
a = np.ones(3, dtype=np.int32)

In [5]:
b = np.linspace(0, pi, 3)

In [6]:
a

array([1, 1, 1])

In [7]:
b

array([0.        , 1.57079633, 3.14159265])

In [8]:
b.dtype.name

'float64'

In [9]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [10]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [11]:
d.dtype.name

'complex128'

In [13]:
b.sum()

4.71238898038469

In [14]:
b.min()

0.0

In [15]:
a.max()

1

In [16]:
e = np.arange(12).reshape(3, 4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
#A soma de cada coluna 
e.sum(axis=0)

array([12, 15, 18, 21])

In [20]:
#O minimo de cada coluna 
e.min(axis=0)

array([0, 1, 2, 3])

In [21]:
#O maximo de cada coluna 
e.max(axis=0)

array([ 8,  9, 10, 11])

In [23]:
#A soma cumulativa de cada linha
e.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)